#!/usr/bin/env bash
set -Eeuo pipefail

# Compatibility entry point. The command generated by the web panel downloads
# node/node-install.sh directly from the panel.
script_dir=""
if script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"; then
    :
else
    script_dir=""
fi
if [[ -n "$script_dir" && -f "$script_dir/node/node-install.sh" ]]; then
    exec bash "$script_dir/node/node-install.sh" "$@"
fi

repo="${GOST_RELAY_NODE_REPO:-666speed/gost-relay-panel}"
ref="${GOST_RELAY_NODE_REF:-main}"
exec bash <(curl -fLSs --retry 3 "https://raw.githubusercontent.com/${repo}/${ref}/node/node-install.sh") "$@"
