#!/usr/bin/env python3
"""GOST Relay node agent: pull TCP/IPv4 rules and apply them atomically."""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import os
import platform
import random
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

try:
    import fcntl
except ImportError:  # pragma: no cover - only used by Windows-side unit tests
    fcntl = None  # type: ignore[assignment]

VERSION = "1.0.0"
STATE_DIR = Path(os.environ.get("GOST_RELAY_STATE_DIR", "/etc/gost-relay-agent"))
AGENT_CONFIG = Path(os.environ.get("GOST_RELAY_AGENT_CONFIG", str(STATE_DIR / "agent.json")))
STATE_FILE = Path(os.environ.get("GOST_RELAY_STATE_FILE", str(STATE_DIR / "state.json")))
GOST_CONFIG = Path(os.environ.get("GOST_RELAY_GOST_CONFIG", str(STATE_DIR / "gost.yml")))
CORE_BIN = os.environ.get("GOST_RELAY_CORE_BIN", "/usr/local/lib/gost-relay-agent/gost-core")
RELAY_SERVICE = os.environ.get("GOST_RELAY_SERVICE", "gost-relay.service")
LOCK_FILE = Path(os.environ.get("GOST_RELAY_LOCK_FILE", str(STATE_DIR / "agent.lock")))
MAX_RULES = 10000
STOP_REQUESTED = False


class AgentError(RuntimeError):
    pass


def log(message: str) -> None:
    print(time.strftime("%Y-%m-%d %H:%M:%S"), message, flush=True)


def normalize_panel_url(value: str) -> str:
    value = value.strip().rstrip("/")
    parsed = urllib.parse.urlparse(value)
    local_http = parsed.scheme == "http" and parsed.hostname in {"127.0.0.1", "localhost"}
    allow_http = os.environ.get("GOST_RELAY_ALLOW_HTTP") == "1"
    if parsed.scheme != "https" and not local_http and not allow_http:
        raise AgentError("面板地址必须使用 HTTPS")
    if not parsed.hostname or parsed.query or parsed.fragment or parsed.username or parsed.password:
        raise AgentError("面板地址格式无效")
    if parsed.path not in {"", "/"}:
        raise AgentError("面板必须部署在域名根目录")
    return value


def valid_port(value: Any) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value <= 65535:
        raise AgentError(f"端口无效: {value!r}")
    return value


def valid_ipv4(value: Any) -> str:
    if not isinstance(value, str):
        raise AgentError("目标地址必须是 IPv4 字符串")
    try:
        address = ipaddress.IPv4Address(value)
    except ipaddress.AddressValueError as exc:
        raise AgentError(f"目标 IPv4 无效: {value}") from exc
    if address.is_unspecified or address.is_multicast or value == "255.255.255.255":
        raise AgentError(f"禁止使用目标 IPv4: {value}")
    return str(address)


def normalize_rules(raw_rules: Any) -> list[dict[str, Any]]:
    if not isinstance(raw_rules, list) or len(raw_rules) > MAX_RULES:
        raise AgentError("规则列表无效或超过 10000 条")
    normalized: list[dict[str, Any]] = []
    ports: set[int] = set()
    ids: set[int] = set()
    for raw in raw_rules:
        if not isinstance(raw, dict):
            raise AgentError("规则必须是对象")
        rule_id = raw.get("id")
        if isinstance(rule_id, bool) or not isinstance(rule_id, int) or rule_id <= 0 or rule_id in ids:
            raise AgentError("规则 ID 无效或重复")
        listen_port = valid_port(raw.get("listen_port"))
        if listen_port in ports:
            raise AgentError(f"监听端口重复: {listen_port}")
        target_port = valid_port(raw.get("target_port"))
        target_ipv4 = valid_ipv4(raw.get("target_ipv4"))
        name = str(raw.get("name", ""))[:100]
        normalized.append({
            "id": rule_id,
            "name": name,
            "listen_port": listen_port,
            "target_ipv4": target_ipv4,
            "target_port": target_port,
        })
        ports.add(listen_port)
        ids.add(rule_id)
    normalized.sort(key=lambda item: (item["listen_port"], item["id"]))
    return normalized


def render_gost_config(raw_rules: Any) -> str:
    rules = normalize_rules(raw_rules)
    lines = [
        "# Generated by GOST Relay agent. Local edits will be overwritten.",
        "# Raw TCP over IPv4 only: no SNI inspection, UDP, or IPv6 listener.",
    ]
    if not rules:
        lines.append("services: []")
    else:
        lines.append("services:")
        for rule in rules:
            lines.extend([
                f'  - name: "relay-{rule["id"]}"',
                f'    addr: "0.0.0.0:{rule["listen_port"]}"',
                "    handler:",
                "      type: tcp",
                "    listener:",
                "      type: tcp",
                "    forwarder:",
                "      nodes:",
                f'        - name: "target-{rule["id"]}"',
                f'          addr: "{rule["target_ipv4"]}:{rule["target_port"]}"',
            ])
    lines.extend(["", "log:", "  output: stderr", "  level: info", "  format: text", ""])
    return "\n".join(lines)


def rules_digest(raw_rules: Any) -> str:
    payload = json.dumps(normalize_rules(raw_rules), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode()).hexdigest()


def atomic_write(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def save_json(path: Path, value: dict[str, Any], mode: int = 0o600) -> None:
    atomic_write(path, json.dumps(value, ensure_ascii=False, indent=2) + "\n", mode)


def load_json(path: Path, default: dict[str, Any] | None = None) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        if default is not None:
            return default.copy()
        raise AgentError(f"文件不存在: {path}")
    except (OSError, json.JSONDecodeError) as exc:
        raise AgentError(f"无法读取 JSON 文件: {path}") from exc
    if not isinstance(value, dict):
        raise AgentError(f"JSON 顶层必须是对象: {path}")
    return value


def run_command(command: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=30)


def service_is_active() -> bool:
    result = run_command(["systemctl", "is-active", "--quiet", RELAY_SERVICE], check=False)
    return result.returncode == 0


def apply_rules(raw_rules: Any) -> str:
    rendered = render_gost_config(raw_rules)
    digest = rules_digest(raw_rules)
    GOST_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix="gost.validate.", suffix=".yml", dir=GOST_CONFIG.parent)
    temporary = Path(temporary_name)
    os.close(fd)
    backup = GOST_CONFIG.with_suffix(".yml.previous")
    had_config = GOST_CONFIG.exists()
    try:
        atomic_write(temporary, rendered, 0o644)
        validation = run_command([CORE_BIN, "-C", str(temporary), "-O", "yaml"], check=False)
        if validation.returncode != 0:
            raise AgentError("GOST 拒绝新配置: " + validation.stderr.strip()[-800:])
        if had_config:
            shutil.copy2(GOST_CONFIG, backup)
        os.replace(temporary, GOST_CONFIG)
        os.chmod(GOST_CONFIG, 0o644)
        restart = run_command(["systemctl", "restart", RELAY_SERVICE], check=False)
        if restart.returncode == 0:
            for _ in range(10):
                time.sleep(0.5)
                if service_is_active():
                    backup.unlink(missing_ok=True)
                    return digest
        reason = restart.stderr.strip() or "服务未进入 active 状态"
        if had_config and backup.exists():
            os.replace(backup, GOST_CONFIG)
            run_command(["systemctl", "restart", RELAY_SERVICE], check=False)
        else:
            atomic_write(GOST_CONFIG, render_gost_config([]), 0o644)
            run_command(["systemctl", "restart", RELAY_SERVICE], check=False)
        raise AgentError("新配置启动失败，已恢复上一版本: " + reason[-800:])
    finally:
        temporary.unlink(missing_ok=True)


def os_description() -> str:
    values: dict[str, str] = {}
    try:
        for line in Path("/etc/os-release").read_text(encoding="utf-8").splitlines():
            if "=" in line:
                key, value = line.split("=", 1)
                values[key] = value.strip().strip('"')
    except OSError:
        pass
    return (values.get("PRETTY_NAME") or platform.platform())[:100]


def node_metadata() -> dict[str, str]:
    return {
        "hostname": socket.gethostname()[:255],
        "os": os_description(),
        "architecture": platform.machine()[:32],
        "agent_version": VERSION,
    }


def api_request(url: str, payload: dict[str, Any], headers: dict[str, str] | None = None) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode()
    request_headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": f"gost-relay-agent/{VERSION}",
    }
    if headers:
        request_headers.update(headers)
    request = urllib.request.Request(url, data=body, headers=request_headers, method="POST")
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            raw = response.read(2 * 1024 * 1024)
    except urllib.error.HTTPError as exc:
        detail = exc.read(2048).decode("utf-8", "replace")
        raise AgentError(f"面板返回 HTTP {exc.code}: {detail[:500]}") from exc
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise AgentError(f"连接面板失败: {exc}") from exc
    try:
        decoded = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise AgentError("面板返回的 JSON 无效") from exc
    if not isinstance(decoded, dict) or decoded.get("ok") is not True:
        raise AgentError("面板拒绝请求: " + str(decoded.get("error", "unknown")))
    return decoded


def enroll(panel_url: str, token: str, name: str) -> None:
    panel_url = normalize_panel_url(panel_url)
    token = token.strip()
    if len(token) < 32 or not name.strip() or len(name.strip()) > 100:
        raise AgentError("安装令牌或节点名称无效")
    response = api_request(panel_url + "/api/v1/enroll", {
        "token": token,
        "name": name.strip(),
        **node_metadata(),
    })
    node_id = response.get("node_id")
    node_secret = response.get("node_secret")
    if not isinstance(node_id, str) or len(node_id) != 36 or not isinstance(node_secret, str) or len(node_secret) < 32:
        raise AgentError("面板未返回有效的节点凭据")
    save_json(AGENT_CONFIG, {
        "panel_url": panel_url,
        "node_id": node_id,
        "node_secret": node_secret,
        "node_name": name.strip(),
        "group": str(response.get("group", "")),
    })
    log(f"节点登记成功: {name.strip()} / {response.get('group', '')}")


def sync_once(config: dict[str, Any]) -> int:
    panel_url = normalize_panel_url(str(config.get("panel_url", "")))
    node_id = str(config.get("node_id", ""))
    node_secret = str(config.get("node_secret", ""))
    if len(node_id) != 36 or len(node_secret) < 32:
        raise AgentError("节点凭据无效，请重新安装")
    state = load_json(STATE_FILE, {"applied_revision": 0, "rules_digest": "", "last_error": ""})
    applied_revision = max(0, int(state.get("applied_revision", 0)))
    response = api_request(
        panel_url + "/api/v1/sync",
        {
            "applied_revision": applied_revision,
            "last_error": str(state.get("last_error", ""))[:2000],
            **node_metadata(),
        },
        {"X-Node-ID": node_id, "Authorization": "Bearer " + node_secret},
    )
    desired_revision = max(0, int(response.get("desired_revision", 0)))
    rules = response.get("rules", [])
    digest = rules_digest(rules)
    config_missing = not GOST_CONFIG.exists()
    if desired_revision != applied_revision or digest != str(state.get("rules_digest", "")) or config_missing:
        log(f"应用配置 REV {desired_revision}，规则 {len(normalize_rules(rules))} 条")
        try:
            applied_digest = apply_rules(rules)
        except AgentError as exc:
            state["last_error"] = str(exc)[:2000]
            save_json(STATE_FILE, state)
            raise
        save_json(STATE_FILE, {
            "applied_revision": desired_revision,
            "rules_digest": applied_digest,
            "last_error": "",
            "updated_at": int(time.time()),
        })
    interval = int(response.get("poll_interval", 15))
    return min(300, max(5, interval))


def signal_handler(_signum: int, _frame: Any) -> None:
    global STOP_REQUESTED
    STOP_REQUESTED = True


def run_forever() -> None:
    if fcntl is None:
        raise AgentError("节点代理只能运行在 Linux 系统")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    os.chmod(STATE_DIR, 0o750)
    with LOCK_FILE.open("a+", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise AgentError("另一个节点代理实例已经在运行") from exc
        signal.signal(signal.SIGTERM, signal_handler)
        signal.signal(signal.SIGINT, signal_handler)
        config = load_json(AGENT_CONFIG)
        backoff = 5
        while not STOP_REQUESTED:
            try:
                interval = sync_once(config)
                backoff = 5
                sleep_for = max(3, interval + random.uniform(-1.5, 1.5))
            except AgentError as exc:
                log("同步失败: " + str(exc))
                sleep_for = backoff + random.uniform(0, 2)
                backoff = min(60, backoff * 2)
            end = time.monotonic() + sleep_for
            while not STOP_REQUESTED and time.monotonic() < end:
                time.sleep(min(1, end - time.monotonic()))


def main() -> int:
    parser = argparse.ArgumentParser(description="GOST Relay node agent")
    subparsers = parser.add_subparsers(dest="command", required=True)
    enroll_parser = subparsers.add_parser("enroll", help="register this node")
    enroll_parser.add_argument("--token", required=True)
    enroll_parser.add_argument("--url", required=True)
    enroll_parser.add_argument("--name", default=socket.gethostname())
    subparsers.add_parser("run", help="run the polling agent")
    subparsers.add_parser("once", help="perform one synchronization")
    render_parser = subparsers.add_parser("render", help="render GOST config from rules JSON")
    render_parser.add_argument("--rules", required=True, help="JSON file or - for stdin")
    render_parser.add_argument("--output", default="-")
    subparsers.add_parser("version")
    args = parser.parse_args()
    try:
        if args.command == "enroll":
            enroll(args.url, args.token, args.name)
        elif args.command == "run":
            run_forever()
        elif args.command == "once":
            sync_once(load_json(AGENT_CONFIG))
        elif args.command == "render":
            source = sys.stdin.read() if args.rules == "-" else Path(args.rules).read_text(encoding="utf-8")
            rendered = render_gost_config(json.loads(source))
            if args.output == "-":
                sys.stdout.write(rendered)
            else:
                atomic_write(Path(args.output), rendered, 0o644)
        elif args.command == "version":
            print(VERSION)
        return 0
    except (AgentError, OSError, ValueError, json.JSONDecodeError) as exc:
        log("错误: " + str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
